---

- name: Run detect script
  hosts: webservers
  tasks:
    - name: Copy script to remote servers
      copy:
        src: detect.sh
        dest: /tmp/detector.sh
        mode: 0775

    - name: Execute script
      command: /tmp/detector.sh
      register: script_output

    - debug:
        var: script_output.stdout_lines
